version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
     - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: leo
      MYSQL_PASSWORD: leoadsbnetwork
      MYSQL_DATABASE: completeBDD
  phpmyadmin:
    depends_on:
     - db
    image: phpmyadmin
    restart: always
    ports:
      - 8084:80
    environment:
      PMA_HOST: db
